version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  build-and-test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Get previous results
          command: |
            export ARTIFACT_LINK="https://circleci.com/api/v1.1/project/github/bormando/wdiopasvci/latest/artifacts"
            curl $ARTIFACT_LINK -H "Circle-Token $CIRCLE_TOKEN" | grep -Eoq '(http|https)://[a-zA-Z0-9./?=_%:-]*' && wget $(curl $ARTIFACT_LINK -q -H "Circle-Token $CIRCLE_TOKEN" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_%:-]*') -q -O allure-previous.zip
            test -f allure-previous.zip && unzip allure-previous.zip -d allure-previous
      - run:
          name: Run tests
          command: |
            npm run test:chrome:headless
            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results
            npm run report:generate
            zip -r allure-report.zip allure-report
      - run:
          when: on_fail
          name: Generate fail results
          command: |
            test -d allure-previous && cp -r allure-previous/allure-report/history allure-results
            npm run report:generate
            zip -r allure-results.zip allure-results
      - store_artifacts:
          path: allure-report.zip

workflows:
  commit:
    jobs:
      - build-and-test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-and-test

